### ISSUE TITLE
permettre de rajouter la recette en texte libre

### ISSUE THREAD

**Issue by trou** [conchyliculture/liste#25]
parce que c'est plus facile

**Comment by conchyliculture** [comment]
juste fais le?

Or do you mean saving the recipe in a JSON somewhere?

**Comment by trou** [comment]
c'est pour rajouter dans liste des courses à la fin, quand on a une recette non récurrente

**Comment by conchyliculture** [comment]
ben ajoute la recette en texte libre, je comprends pas ce qu'il manque

**Comment by trou** [comment]
en effet.
